name: Build Executable

on:
  push:
    branches:
      - main  # 触发主分支的提交事件

jobs:
  build_windows:
    runs-on: windows-latest  # 在 Windows 环境下运行

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # 检出代码到工作环境

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # 设置 Python 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # 安装依赖，确保 requirements.txt 中包含 tkinter 依赖
    
    - name: Install PyInstaller
      run: 
        pip install pyinstaller

    - name: Build Windows executable
      run: |
        pyinstaller --onefile app.py
    
    - name: Upload executable to Releases
      id: upload-release-assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist/app.exe  # 替换为你的可执行文件路径
        asset_name: app.exe  # 可执行文件的名称
        asset_content_type: application/octet-stream
        token: ${{ secrets.GITHUB_TOKEN }}  # GitHub 提供的默认 token

  build_linux:
    runs-on: ubuntu-latest  # 在 Linux 环境下运行

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # 检出代码到工作环境

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # 设置 Python 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # 安装依赖，确保 requirements.txt 中包含 tkinter 依赖
    - name: Install PyInstaller
      run: 
        pip install pyinstaller

    - name: Build Linux executable
      run: |
        pyinstaller --onefile app.py
    
    - name: Upload executable to Releases
      id: upload-release-assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist/app  # 替换为你的可执行文件路径
        asset_name: app  # 可执行文件的名称
        asset_content_type: application/octet-stream
        token: ${{ secrets.GITHUB_TOKEN }}  # GitHub 提供的默认 token